name: Flutter CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ~/.flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.33.0'
      - run: flutter pub get
      - run: flutter test --coverage
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build_ios:
    needs: build_android
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.33.0'
      - run: |
          sudo gem install cocoapods
          pod install --project-directory=ios
      - run: flutter pub get
      - run: flutter test
      - run: flutter build ios --no-codesign
      - uses: actions/upload-artifact@v2
        with:
          name: ios-build
          path: build/ios/iphoneos
